import { PageIntroAccordion } from '../common/PageIntroAccordion';
import React, { useState } from 'react';
import { motion } from 'motion/react';
import { ArrowLeft, Check, Clock3, Compass, Layers3, Play, Sparkles } from 'lucide-react';
import { Journey } from '../../types';
import { toPersianDigits } from '../../utils/persianDate';
interface Props { journeys: Journey[]; completedStages: Record<string, number[]>; onSelectJourney: (journey: Journey) => void; }
const labels: Record<string,string> = { all:'همه', conflict:'کاهش تنش', trauma:'الگوهای گذشته', intimacy:'صمیمیت', family:'مرزها', communication:'گفت‌وگو' };
export const JourneysTab: React.FC<Props> = ({ journeys, completedStages, onSelectJourney }) => { const [filter,setFilter]=useState('all'); const list=filter==='all'?journeys:journeys.filter(x=>x.category===filter); return <div className="max-w-2xl mx-auto px-4 pt-2 pb-28" dir="rtl"><PageIntroAccordion kind="journeys" /><div className="flex gap-2 overflow-x-auto no-scrollbar pb-5">{['all',...Array.from(new Set(journeys.map(x=>x.category)))].map(item=><button key={item} onClick={()=>setFilter(item)} className={`shrink-0 min-h-10 px-4 rounded-full text-xs font-black ${filter===item?'bg-[oklch(35%_0.04_330)] text-white':'bg-slate-100 dark:bg-slate-800 text-slate-500'}`}>{labels[item]||item}</button>)}</div><div className="space-y-4">{list.map((journey,index)=>{const done=completedStages[journey.id]||[];const percent=Math.round(done.length/journey.stages.length*100);return <motion.button key={journey.id} initial={{opacity:0,y:14}} animate={{opacity:1,y:0}} transition={{delay:index*.05}} onClick={()=>onSelectJourney(journey)} className="w-full text-right rounded-[1.8rem] bg-white dark:bg-slate-900 border border-slate-200 dark:border-slate-800 overflow-hidden shadow-[0_10px_30px_oklch(25%_0.03_330_/_0.05)]"><div className="p-5 pb-4 flex items-start gap-4"><span className="w-12 h-12 rounded-2xl bg-[oklch(94%_0.03_175)] text-[oklch(47%_0.1_175)] flex items-center justify-center shrink-0"><Layers3 size={22}/></span><div className="flex-1"><div className="flex items-center gap-2 text-[11px] text-slate-400"><span>{labels[journey.category]||journey.category}</span><span>•</span><span className="inline-flex items-center gap-1"><Clock3 size={12}/>{journey.estimatedWeeks||journey.estimatedDuration}</span></div><h2 className="mt-2 text-lg font-black text-slate-900 dark:text-white">{journey.title}</h2><p className="mt-1 text-sm leading-6 text-slate-500 dark:text-slate-400 line-clamp-2">{journey.description}</p></div></div><div className="px-5 pb-5"><div className="flex justify-between text-[11px] font-black text-slate-500 mb-2"><span>{done.length?`${toPersianDigits(done.length)} ایستگاه طی شده`:'از ایستگاه اول شروع کن'}</span><span>{toPersianDigits(percent)}٪</span></div><div className="h-2 rounded-full bg-slate-100 dark:bg-slate-800 overflow-hidden"><div className="h-full rounded-full bg-[oklch(59%_0.10_175)]" style={{width:`${percent}%`}}/></div><div className="mt-4 flex items-center justify-between text-xs font-black text-[oklch(50%_0.13_330)]"><span className="inline-flex items-center gap-2">{done.length?<Check size={15}/>:<Play size={15}/>} {done.length?'ادامه مسیر':'شروع مسیر'}</span><ArrowLeft size={16}/></div></div></motion.button>})}</div></div> };
