import React,{useRef,useState} from 'react';
import {Activity,BellRing,CalendarHeart,ChevronDown,Database,Download,FileDown,FileUp,HelpCircle,MoonStar,Save,ShieldCheck,Trash2,UserRound,Wind} from 'lucide-react';
import {motion} from 'motion/react';
import {UserPreferences,MenstrualCycleConfig} from '../../types';
import {PageIntroAccordion} from '../common/PageIntroAccordion';
import {JalaliDatePicker} from '../common/JalaliDatePicker';
import {StorageService} from '../../services/storage';

interface Props{preferences:UserPreferences;darkMode:boolean;onToggleDarkMode:()=>void;onUpdatePreferences:(prefs:Partial<UserPreferences>)=>void;onNotificationToggle:(enabled:boolean)=>Promise<boolean>;onResetAll:()=>void;cycleConfig:MenstrualCycleConfig;onUpdateCycleConfig:(config:MenstrualCycleConfig)=>void;}
export const SettingsTab:React.FC<Props>=({preferences,onUpdatePreferences,onNotificationToggle,onResetAll,cycleConfig,onUpdateCycleConfig})=>{
 const [confirm,setConfirm]=useState(false),[guide,setGuide]=useState(false),[saved,setSaved]=useState(false),[notificationBusy,setNotificationBusy]=useState(false),fileRef=useRef<HTMLInputElement>(null);
 const [name,setName]=useState(preferences.userName||''),[partner,setPartner]=useState(preferences.partnerName||''),[anniversary,setAnniversary]=useState(preferences.anniversaryDate||'');
 const saveProfile=()=>{onUpdatePreferences({userName:name.trim(),partnerName:partner.trim(),anniversaryDate:anniversary});setSaved(true);setTimeout(()=>setSaved(false),1800)};
 const backup=()=>{const data:Record<string,string>={};for(let i=0;i<localStorage.length;i++){const k=localStorage.key(i);if(k&&k.startsWith('yar_'))data[k]=localStorage.getItem(k)||'';}const blob=new Blob([JSON.stringify({app:'yar',version:1,createdAt:new Date().toISOString(),data},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='yar-backup.json';a.click();URL.revokeObjectURL(url)};
 const restore=(e:React.ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;const reader=new FileReader();reader.onload=()=>{try{const parsed=JSON.parse(String(reader.result));Object.entries(parsed.data||{}).forEach(([k,v])=>{if(k.startsWith('yar_'))localStorage.setItem(k,String(v))});location.reload()}catch{alert('فایل پشتیبان معتبر نیست.')}};reader.readAsText(f)};
 return <div className="mx-auto max-w-md space-y-4 px-4 pb-28 pt-3" dir="rtl"><PageIntroAccordion kind="settings"/>
  <section className="rounded-[1.7rem] border border-[oklch(89%_0.025_300)] bg-white p-5 shadow-soft-card dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[oklch(92%_0.045_300)] text-[oklch(48%_0.14_300)]"><UserRound size={21}/></span><div><h2 className="text-base font-black">اطلاعات شخصی</h2><p className="mt-1 text-xs text-slate-500">برای پیشنهادهای شخصی‌تر رابطه</p></div></div><div className="mt-5 space-y-3"><label className="block text-xs font-black">نام تو<input value={name} onChange={e=>setName(e.target.value)} placeholder="مثلاً سارا" className="mt-2 min-h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm dark:border-slate-700 dark:bg-slate-800"/></label><label className="block text-xs font-black">نام همراه<input value={partner} onChange={e=>setPartner(e.target.value)} placeholder="مثلاً علی" className="mt-2 min-h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 text-sm dark:border-slate-700 dark:bg-slate-800"/></label><div><p className="mb-2 text-xs font-black">تاریخ ازدواج یا آشنایی</p><JalaliDatePicker value={anniversary} onChange={setAnniversary} labelFa="تاریخ مهم رابطه" allowFuture={false}/></div><button onClick={saveProfile} className="flex min-h-12 w-full items-center justify-center gap-2 rounded-2xl bg-[oklch(52%_0.16_300)] text-sm font-black text-white">{saved?<><Save size={17}/> ذخیره شد</>:<><Save size={17}/> ذخیره اطلاعات</>}</button></div></section>
  <section className="rounded-[1.7rem] border border-[oklch(89%_0.025_300)] bg-white p-5 shadow-soft-card dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[oklch(94%_0.035_330)] text-[oklch(52%_0.14_330)]"><MoonStar size={21}/></span><div><h2 className="text-base font-black">چرخه و PMS</h2><p className="mt-1 text-xs text-slate-500">تنظیمات چرخه را از همین‌جا مدیریت کن</p></div></div><div className="mt-4 grid grid-cols-2 gap-3"><label className="text-xs font-black">طول چرخه<input type="number" min="18" max="60" value={cycleConfig.cycleLengthDays} onChange={e=>onUpdateCycleConfig(StorageService.saveCycleConfig({...cycleConfig,cycleLengthDays:Math.min(60,Math.max(18,Number(e.target.value)||28))}))} className="mt-2 min-h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 dark:border-slate-700 dark:bg-slate-800"/></label><label className="text-xs font-black">روز خون‌ریزی<input type="number" min="2" max="10" value={cycleConfig.periodLengthDays} onChange={e=>onUpdateCycleConfig(StorageService.saveCycleConfig({...cycleConfig,periodLengthDays:Math.min(10,Math.max(2,Number(e.target.value)||5))}))} className="mt-2 min-h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 dark:border-slate-700 dark:bg-slate-800"/></label></div><label className="mt-3 block text-xs font-black">شروع PMS، چند روز قبل<select value={cycleConfig.pmsStartDaysBefore??7} onChange={e=>onUpdateCycleConfig(StorageService.saveCycleConfig({...cycleConfig,pmsStartDaysBefore:Number(e.target.value)}))} className="mt-2 min-h-11 w-full rounded-xl border border-slate-200 bg-slate-50 px-3 dark:border-slate-700 dark:bg-slate-800"><option value="0">بدون پیش‌بینی PMS</option><option value="5">۵ روز</option><option value="7">۷ روز</option><option value="10">۱۰ روز</option></select></label></section>
  <section className="rounded-[1.7rem] border border-[oklch(88%_0.035_325)] bg-[oklch(98%_0.012_325)] p-5 shadow-soft-card dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[oklch(91%_0.06_325)] text-[oklch(48%_0.16_325)]"><BellRing size={21}/></span><span className="flex-1"><h2 className="text-base font-black">دو جمله روزانه</h2><p className="mt-1 text-xs text-slate-500">صبح ۱۰ و شب ۲۰:۳۰، هر روز تازه</p></span><button disabled={notificationBusy} aria-label="تغییر وضعیت اعلان‌ها" onClick={async()=>{setNotificationBusy(true);await onNotificationToggle(!preferences.notificationsEnabled);setNotificationBusy(false)}} className={`relative h-7 w-12 rounded-full p-1 transition-colors disabled:opacity-50 ${preferences.notificationsEnabled?'bg-[oklch(52%_0.16_325)]':'bg-slate-300 dark:bg-slate-700'}`}><span className={`block h-5 w-5 rounded-full bg-white shadow-sm transition-transform ${preferences.notificationsEnabled?'-translate-x-5':''}`}/></button></div><div className="mt-4 flex items-center justify-between rounded-2xl bg-white px-4 py-3 dark:bg-slate-800"><span className="text-xs font-bold text-slate-600 dark:text-slate-200">{notificationBusy?'در حال بررسی مجوز...':preferences.notificationsEnabled?'اعلان‌ها فعال‌اند':'اعلان‌ها خاموش‌اند'}</span><span className={`h-2.5 w-2.5 rounded-full ${preferences.notificationsEnabled?'bg-emerald-500':'bg-slate-300'}`}/></div></section>
  <section className="rounded-[1.7rem] border border-[oklch(89%_0.025_300)] bg-white p-5 shadow-soft-card dark:border-slate-800 dark:bg-slate-900"><div className="flex items-center gap-3"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[oklch(93%_0.04_175)] text-[oklch(48%_0.1_175)]"><Database size={21}/></span><div><h2 className="text-base font-black">پشتیبان و حریم داده</h2><p className="mt-1 text-xs text-slate-500">اطلاعات یار فقط روی همین دستگاه است</p></div></div><div className="mt-4 grid grid-cols-2 gap-2"><button onClick={backup} className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[oklch(94%_0.04_175)] text-xs font-black text-[oklch(40%_0.1_175)]"><Download size={16}/> دریافت پشتیبان</button><button onClick={()=>fileRef.current?.click()} className="flex min-h-11 items-center justify-center gap-2 rounded-xl bg-[oklch(94%_0.035_300)] text-xs font-black text-[oklch(43%_0.13_300)]"><FileUp size={16}/> بازیابی فایل</button></div><input ref={fileRef} type="file" accept="application/json" onChange={restore} className="hidden"/></section>
  <section className="overflow-hidden rounded-[1.7rem] border border-[oklch(89%_0.025_300)] bg-white dark:border-slate-800 dark:bg-slate-900"><button onClick={()=>setGuide(v=>!v)} className="flex min-h-14 w-full items-center gap-3 px-5 text-right"><HelpCircle size={20} className="text-[oklch(52%_0.14_300)]"/><span className="flex-1"><b className="block text-sm font-black">راهنمای استفاده از یار</b><small className="text-[11px] text-slate-500">چطور از بخش‌ها بهترین استفاده را ببری</small></span><ChevronDown size={17} className={`text-slate-400 transition-transform ${guide?'rotate-180':''}`}/></button>{guide&&<motion.div initial={{opacity:0}} animate={{opacity:1}} className="space-y-3 border-t border-slate-100 px-5 pb-5 pt-4 text-xs leading-6 text-slate-600 dark:border-slate-800 dark:text-slate-300"><p><b>خانه:</b> پیشنهادهای روزانه و جمله امروز را ببین.</p><p><b>اتاق ما:</b> حال رابطه، خاطره‌ها و قرارها را ثبت کن.</p><p><b>چرخه:</b> تاریخ شروع، طول چرخه، خون‌ریزی و PMS را تنظیم کن.</p><p><b>تمرین‌ها:</b> یک تمرین کوتاه انتخاب کن و نتیجه‌اش را ثبت کن.</p></motion.div>}</section>
  <section className="rounded-[1.7rem] border border-rose-200 bg-rose-50 p-5 dark:border-rose-900/40 dark:bg-rose-950/25"><h2 className="flex items-center gap-2 text-sm font-black text-rose-700 dark:text-rose-300"><Trash2 size={17}/> پاک‌کردن داده‌ها</h2>{!confirm?<button onClick={()=>setConfirm(true)} className="mt-3 min-h-11 w-full rounded-xl bg-rose-100 text-xs font-black text-rose-700 dark:bg-rose-900/40 dark:text-rose-300">حذف همه داده‌های این دستگاه</button>:<div className="mt-3"><p className="text-xs leading-5 text-rose-700 dark:text-rose-300">این کار قابل برگشت نیست.</p><div className="mt-3 flex gap-2"><button onClick={onResetAll} className="min-h-10 flex-1 rounded-xl bg-rose-600 text-xs font-black text-white">حذف کن</button><button onClick={()=>setConfirm(false)} className="min-h-10 flex-1 rounded-xl border border-rose-300 text-xs font-black text-rose-700">انصراف</button></div></div>}</section>
 </div>;
};
