import React,{useEffect} from 'react';
import {AnimatePresence,motion} from 'motion/react';
import {Activity,BookOpen,ChevronLeft,Compass,HeartHandshake,Home,Menu,MessageCircleHeart,Moon,MoonStar,Settings,ShieldAlert,Sparkles,Sun,X} from 'lucide-react';
import {ActiveTab} from '../../types';
import {AppIcon} from '../common/AppIcon';
interface Props{isOpen:boolean;onClose:()=>void;activeTab:ActiveTab;onSelectTab:(tab:ActiveTab)=>void;darkMode:boolean;onToggleDarkMode:()=>void;streakCount:number;userName?:string;onOpenSOS:()=>void;}
const ITEMS:{tab:ActiveTab;label:string;caption:string;icon:React.ReactNode}[]=[
 {tab:'home',label:'خانه',caption:'پیشنهادهای امروز',icon:<Home size={20}/>},
 {tab:'library',label:'کتابخانه',caption:'کتاب‌ها، فصل‌ها و مطالعه آرام',icon:<BookOpen size={20}/>},
 {tab:'library-old',label:'نکات زندگی',caption:'مقالات و نکته‌های کاربردی رابطه',icon:<Sparkles size={20}/>},
 {tab:'journeys',label:'مسیرها',caption:'یادگیری قدم‌به‌قدم',icon:<Compass size={20}/>},
 {tab:'exercises',label:'تمرین‌ها',caption:'تمرین‌های رابطه و آرام‌سازی',icon:<Sparkles size={20}/>},
 {tab:'couple',label:'فضای دونفره',caption:'چک‌این، خاطره و قرار',icon:<HeartHandshake size={20}/>},
 {tab:'cycle',label:'چرخه قاعدگی',caption:'فازها، PMS و حال امروز',icon:<MoonStar size={20}/>},
 {tab:'profile',label:'تنظیمات',caption:'شخصی‌سازی و داده‌های دستگاه',icon:<Settings size={20}/>},
];
export const ExpandedMenu:React.FC<Props>=({isOpen,onClose,activeTab,onSelectTab,darkMode,onToggleDarkMode,streakCount,userName,onOpenSOS})=>{useEffect(()=>{document.body.style.overflow=isOpen?'hidden':'';return()=>{document.body.style.overflow=''}},[isOpen]);const go=(tab:ActiveTab)=>{onSelectTab(tab);onClose()};return <AnimatePresence>{isOpen&&<div className="fixed inset-0 z-[55]" dir="rtl"><motion.button aria-label="بستن منو" onClick={onClose} initial={{opacity:0}} animate={{opacity:1}} exit={{opacity:0}} className="absolute inset-0 bg-slate-950/35"/><motion.aside initial={{x:'100%'}} animate={{x:0}} exit={{x:'100%'}} transition={{duration:.28,ease:[.16,1,.3,1]}} className="absolute inset-y-0 right-0 flex w-[82%] max-w-[22rem] flex-col overflow-hidden rounded-l-[2rem] bg-[oklch(98%_0.008_300)] shadow-2xl dark:bg-slate-950" drag="x" dragDirectionLock dragConstraints={{left:0,right:0}} dragElastic={{left:0,right:.85}} dragMomentum={false} onDragEnd={(_,info)=>{if(info.offset.x>80||info.velocity.x>420)onClose();}}>
 <header className="shrink-0 border-b border-[oklch(91%_0.018_300)] px-4 pb-4 pt-[calc(env(safe-area-inset-top)+.85rem)] dark:border-slate-800"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><AppIcon size={42} rounded/><div><b className="block text-base text-slate-900 dark:text-white">{userName||'یار'}</b><small className="text-[11px] text-slate-500">همراه رابطه‌ای آگاهانه‌تر</small></div></div><button onClick={onClose} aria-label="بستن منو" className="flex h-10 w-10 items-center justify-center rounded-xl bg-slate-100 text-slate-500 dark:bg-slate-900"><X size={18}/></button></div><div className="mt-4 flex items-center justify-between rounded-2xl bg-[oklch(95%_0.025_80)] px-3 py-2.5 text-xs dark:bg-amber-950/25"><span className="font-bold text-slate-700 dark:text-slate-300">پیشرفت این هفته</span><span className="font-black text-[oklch(52%_0.12_80)]">{streakCount?`${streakCount} روز پیوسته`:'هنوز شروع نشده'}</span></div></header>
 <div className="flex-1 overflow-y-auto px-3 py-3"><p className="px-2 pb-2 text-[11px] font-black text-slate-400">بخش‌های واقعی برنامه</p><div className="space-y-1">{ITEMS.map((item,index)=>{const active=activeTab===item.tab;return <motion.button key={item.tab} initial={{opacity:0,x:10}} animate={{opacity:1,x:0}} transition={{delay:index*.025}} onClick={()=>go(item.tab)} className={`flex min-h-[3.55rem] w-full items-center gap-3 rounded-2xl px-3 text-right transition-colors ${active?'bg-[oklch(93%_0.045_330)] text-[oklch(40%_0.13_330)] dark:bg-pink-950/35 dark:text-pink-200':'text-slate-700 hover:bg-slate-100 dark:text-slate-300 dark:hover:bg-slate-900'}`}><span className={active?'text-[oklch(52%_0.16_330)]':'text-slate-400 dark:text-slate-500'}>{item.icon}</span><span className="min-w-0 flex-1"><b className="block text-sm font-black">{item.label}</b><small className="mt-0.5 block truncate text-[10px] text-slate-500 dark:text-slate-400">{item.caption}</small></span>{active?<span className="h-2 w-2 rounded-full bg-[oklch(58%_0.17_330)]"/>:<ChevronLeft size={15} className="text-slate-300"/>}</motion.button>})}</div><button onClick={()=>{onClose();onOpenSOS();}} className="mt-3 flex min-h-12 w-full items-center gap-3 rounded-2xl bg-rose-50 px-3 text-right text-rose-700 dark:bg-rose-950/30 dark:text-rose-300"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-rose-500 text-white"><ShieldAlert size={17}/></span><span><b className="block text-xs font-black">SOS آرام‌سازی فوری</b><small className="text-[10px]">برای لحظه‌های تنش شدید</small></span></button></div>
 <footer className="flex shrink-0 items-center justify-between border-t border-[oklch(91%_0.018_300)] px-4 py-3 dark:border-slate-800"><span className="text-[10px] text-slate-400">نسخه ۲.۵ یار</span><button onClick={onToggleDarkMode} className="flex h-10 items-center gap-2 rounded-xl bg-slate-100 px-3 text-xs font-bold text-slate-600 dark:bg-slate-900 dark:text-slate-300">{darkMode?<Sun size={16}/>:<Moon size={16}/>} {darkMode?'حالت روشن':'حالت شب'}</button></footer>
 </motion.aside></div>}</AnimatePresence>};
