import React, { useEffect, useRef, useState } from 'react';
import { AppIcon } from '../common/AppIcon';
import { Bell, BellRing, ChevronLeft, Heart, HeartPulse, Menu, ShieldAlert, Sparkles } from 'lucide-react';

type NotificationTarget = 'home'|'couple'|'cycle';
interface NavbarNotification { id:string; title:string; body:string; tone:'calm'|'warm'|'attention'; target:NotificationTarget; }
interface NavbarProps { streakCount:number; onOpenSOS:()=>void; onOpenMenu:()=>void; notifications:NavbarNotification[]; onNotificationNavigate:(target:NotificationTarget)=>void; }
export const Navbar: React.FC<NavbarProps> = ({ onOpenSOS, onOpenMenu, notifications, onNotificationNavigate }) => {
  const [showNotifications,setShowNotifications]=useState(false);
  const panelRef=useRef<HTMLDivElement>(null);
  useEffect(()=>{if(!showNotifications)return;const close=(event:PointerEvent)=>{if(panelRef.current&&!panelRef.current.contains(event.target as Node))setShowNotifications(false)};document.addEventListener('pointerdown',close);return()=>document.removeEventListener('pointerdown',close)},[showNotifications]);
  const go=(target:NotificationTarget)=>{setShowNotifications(false);onNotificationNavigate(target)};
  const iconFor=(item:NavbarNotification,index:number)=>index < 2 ? <span className="relative inline-flex"><Bell size={17}/><Heart size={9} className="absolute -bottom-1 -left-1 fill-current"/></span> : item.tone==='attention'?<HeartPulse size={17}/>:<Sparkles size={17}/>;
  const styleFor=(item:NavbarNotification,index:number)=>index < 2 ? 'bg-[oklch(93%_0.065_345)] text-[oklch(52%_0.17_345)]' : item.tone==='attention'?'bg-[oklch(93%_0.05_20)] text-[oklch(48%_0.16_20)]':'bg-[oklch(93%_0.045_155)] text-[oklch(44%_0.11_155)]';
  return <header className="yar-header" dir="rtl"><div ref={panelRef} className="yar-header-card relative">
    <div className="flex min-w-0 items-center gap-2"><button onClick={onOpenMenu} aria-label="باز کردن منو" className="flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl border border-slate-200/70 bg-slate-100/90 text-slate-600 transition-transform active:scale-95 dark:border-slate-700/60 dark:bg-slate-800/80 dark:text-slate-300"><Menu size={21}/></button><button onClick={onOpenMenu} className="flex min-w-0 items-center gap-2 rounded-2xl text-right transition-transform active:scale-95"><div className="relative shrink-0"><AppIcon size={35} rounded/><span className="absolute -right-0.5 -top-0.5 h-2.5 w-2.5 rounded-full border-2 border-white bg-emerald-400 dark:border-slate-900"/></div><span className="text-base font-black text-slate-900 dark:text-white">یار</span></button></div>
    <div className="flex shrink-0 items-center gap-1.5"><button onClick={onOpenSOS} aria-label="آرام‌سازی فوری" title="آرام‌سازی فوری" className="flex h-11 w-11 items-center justify-center rounded-2xl border border-rose-200/70 bg-rose-50 text-rose-600 transition-transform active:scale-95 dark:border-rose-900/40 dark:bg-rose-950/45 dark:text-rose-300"><ShieldAlert size={19}/></button><button onClick={()=>setShowNotifications(v=>!v)} aria-expanded={showNotifications} aria-label="اعلان‌ها" className={`relative flex h-11 w-11 items-center justify-center rounded-2xl border transition-all active:scale-95 ${showNotifications?'border-[oklch(72%_0.09_325)] bg-[oklch(91%_0.055_325)] text-[oklch(46%_0.16_325)]':'border-slate-200/70 bg-slate-100/90 text-slate-600 dark:border-slate-700/60 dark:bg-slate-800/80 dark:text-slate-300'}`}><Bell size={19}/><span className="absolute right-2 top-2 h-2 w-2 rounded-full border border-white bg-[oklch(58%_0.2_25)] dark:border-slate-900"/></button></div>
    {showNotifications&&<div className="absolute right-0 top-full z-30 mt-2 w-[min(22rem,calc(100vw-1.5rem))] overflow-hidden rounded-[1.7rem] border border-[oklch(90%_0.025_320)] bg-[oklch(99%_0.008_320)] shadow-[0_24px_60px_-20px_oklch(35%_0.06_310_/_0.35)] dark:border-slate-700 dark:bg-[oklch(19%_0.025_290)]">
      <div className="flex items-center gap-3 bg-[oklch(95%_0.04_325)] px-4 py-4 dark:bg-[oklch(24%_0.05_310)]"><span className="flex h-11 w-11 items-center justify-center rounded-2xl bg-[oklch(50%_0.17_325)] text-white"><BellRing size={20}/></span><span className="flex-1"><b className="block text-sm text-slate-900 dark:text-white">تلنگرهای امروز</b><small className="mt-1 block text-[10px] text-slate-500 dark:text-slate-300">دو جمله تازه، صبح و شب</small></span><span className="rounded-full bg-white px-2.5 py-1 text-[10px] font-black text-[oklch(48%_0.15_325)] dark:bg-slate-800">۲ جمله</span></div>
      <div className="px-3 py-3">{notifications.map((item,index)=><React.Fragment key={item.id}>{index===2&&<div className="mx-2 my-2 flex items-center gap-2"><span className="h-px flex-1 bg-[oklch(91%_0.015_320)] dark:bg-slate-700"/><small className="text-[9px] font-black text-slate-400">پیشنهاد شخصی یار</small><span className="h-px flex-1 bg-[oklch(91%_0.015_320)] dark:bg-slate-700"/></div>}<button onClick={()=>go(item.target)} className="group flex min-h-[4.3rem] w-full items-center gap-3 rounded-[1.25rem] px-2.5 text-right transition-colors hover:bg-[oklch(96%_0.02_320)] active:bg-[oklch(93%_0.035_320)] dark:hover:bg-slate-800"><span className={`flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl ${styleFor(item,index)}`}>{iconFor(item,index)}</span><span className="min-w-0 flex-1"><b className="block text-xs text-slate-800 dark:text-white">{item.title}</b><span className="mt-1 block overflow-hidden text-ellipsis whitespace-nowrap text-[11px] text-slate-500 dark:text-slate-300">{item.body}</span></span><ChevronLeft size={15} className="shrink-0 text-slate-300 transition-transform group-active:-translate-x-0.5"/></button></React.Fragment>)}</div>
      <p className="px-4 pb-4 text-center text-[9px] leading-5 text-slate-400">فردا دو جمله کاملاً تازه اینجا می‌بینی</p>
    </div>}
  </div></header>;
};
