import React, { useState } from 'react';
import { AppIcon } from '../common/AppIcon';
import { Bell, Flame, Menu, ShieldAlert, X } from 'lucide-react';
import { toPersianDigits } from '../../utils/persianDate';

interface NavbarNotification { id:string; title:string; body:string; tone:'calm'|'warm'|'attention'; }
interface NavbarProps { streakCount:number; onOpenSOS:()=>void; onOpenMenu:()=>void; notifications:NavbarNotification[]; }
export const Navbar: React.FC<NavbarProps> = ({ streakCount, onOpenSOS, onOpenMenu, notifications }) => {
  const [showNotifications, setShowNotifications] = useState(false);
  return <header className="yar-header" dir="rtl">
    <div className="yar-header-card relative">
      <div className="flex items-center gap-2 min-w-0"><button onClick={onOpenMenu} aria-label="باز کردن منو" className="w-11 h-11 shrink-0 rounded-2xl bg-slate-100/90 dark:bg-slate-800/80 border border-slate-200/70 dark:border-slate-700/60 text-slate-600 dark:text-slate-300 flex items-center justify-center active:scale-95"><Menu size={21}/></button><button onClick={onOpenMenu} className="flex items-center gap-2 min-w-0 text-right rounded-2xl active:scale-95"><div className="relative shrink-0"><AppIcon size={35} rounded/><span className="absolute -top-0.5 -right-0.5 w-2.5 h-2.5 rounded-full bg-emerald-400 border-2 border-white dark:border-slate-900"/></div><span className="text-base font-black text-slate-900 dark:text-white">یار</span></button></div>
      <div className="flex items-center gap-1.5 shrink-0"><button onClick={onOpenSOS} aria-label="آرام‌سازی فوری" title="آرام‌سازی فوری" className="w-11 h-11 rounded-2xl bg-rose-50 dark:bg-rose-950/45 text-rose-600 dark:text-rose-300 border border-rose-200/70 dark:border-rose-900/40 flex items-center justify-center active:scale-95"><ShieldAlert size={19}/></button><button onClick={()=>setShowNotifications(v=>!v)} aria-label="اعلان‌ها" className="relative w-11 h-11 rounded-2xl bg-slate-100/90 dark:bg-slate-800/80 border border-slate-200/70 dark:border-slate-700/60 text-slate-600 dark:text-slate-300 flex items-center justify-center active:scale-95"><Bell size={19}/><span className="absolute top-2 right-2 w-2 h-2 rounded-full bg-rose-500 border border-white dark:border-slate-900"/></button><div className="h-11 px-3 rounded-2xl bg-amber-50 dark:bg-slate-800/80 border border-amber-100/80 dark:border-slate-700/60 flex items-center gap-1 text-[11px] font-black"><Flame size={16} className="fill-amber-400 text-amber-500"/><span className="text-slate-800 dark:text-slate-200">{toPersianDigits(streakCount)}</span></div></div>
      {showNotifications&&<div className="absolute top-[4.6rem] left-3 z-30 w-[min(19rem,calc(100vw-2rem))] rounded-[1.5rem] bg-[oklch(98%_0.008_330)] dark:bg-slate-900 border border-slate-200 dark:border-slate-700 shadow-2xl p-4"><div className="flex items-center justify-between mb-3"><b className="text-sm text-slate-900 dark:text-white">اعلان‌های یار</b><button onClick={()=>setShowNotifications(false)} className="text-slate-400"><X size={16}/></button></div><div className="space-y-2">{notifications.map(item=><div key={item.id} className={`flex gap-3 p-3 rounded-2xl ${item.tone==='attention'?'bg-rose-50 dark:bg-rose-950/25':item.tone==='warm'?'bg-emerald-50 dark:bg-emerald-950/25':'bg-[oklch(94%_0.035_330)] dark:bg-pink-950/20'}`}><span className="w-9 h-9 rounded-xl bg-[oklch(53%_0.14_330)] text-white flex items-center justify-center shrink-0"><Bell size={16}/></span><div><b className="block text-xs text-slate-900 dark:text-white">{item.title}</b><p className="mt-1 text-[11px] leading-5 text-slate-600 dark:text-slate-300">{item.body}</p></div></div>)}</div></div>}
    </div>
  </header>;
};
