import React, { useEffect, useState } from 'react';
import { AnimatePresence, motion } from 'motion/react';
import { ArrowLeft, ArrowRight, Check, CheckCircle2, ChevronDown, ChevronUp, Clock, Save, ShieldAlert, Sparkles, Timer, User, Users, X } from 'lucide-react';
import { Exercise } from '../../types';
import { toPersianDigits } from '../../utils/persianDate';
import { StorageService } from '../../services/storage';

interface Props { exercise: Exercise | null; isOpen: boolean; onClose: () => void; isCompleted: boolean; onToggleCompleted: (id: string) => void; }
const safetyText = 'این تمرین نیازمند آرامش اولیه است. اگر در این لحظه در اوج دعوا هستید یا ترس وجود دارد، ابتدا وقفه بگیرید و از تمرین‌های آرام‌سازی انفرادی استفاده کنید.';
const cleanTitle = (title: string) => title.replace(/\s*\([^)]*[A-Za-z][^)]*\)/g, '').replace(/\s+(Time-Out|Repair Attempts|Fight|Flight|Freeze|Fawn)\b/gi, '').trim();

export const ExerciseModal: React.FC<Props> = ({ exercise, isOpen, onClose, isCompleted, onToggleCompleted }) => {
  const [step, setStep] = useState(0); const [note, setNote] = useState(''); const [saved, setSaved] = useState(false);
  const [seconds, setSeconds] = useState(0); const [running, setRunning] = useState(false); const [showInfo, setShowInfo] = useState(false); const [showSafety, setShowSafety] = useState(true);
  useEffect(() => { if (exercise && isOpen) { setStep(0); setNote(StorageService.getExerciseNote(exercise.id)); setSeconds(exercise.duration * 60); setRunning(false); setShowInfo(false); setShowSafety(localStorage.getItem('yar-exercise-safety-seen') !== '1'); } }, [exercise, isOpen]);
  useEffect(() => { if (!running || seconds <= 0) return; const id = window.setInterval(() => setSeconds(v => Math.max(0, v - 1)), 1000); return () => window.clearInterval(id); }, [running, seconds]);
  if (!isOpen || !exercise) return null;
  const current = exercise.steps[step];
  const time = `${toPersianDigits(Math.floor(seconds / 60))}:${toPersianDigits(String(seconds % 60).padStart(2, '0'))}`;
  const dismissSafety = () => { localStorage.setItem('yar-exercise-safety-seen', '1'); setShowSafety(false); };
  const saveNote = () => { StorageService.saveExerciseNote(exercise.id, note); setSaved(true); window.setTimeout(() => setSaved(false), 1800); };
  const finish = () => { saveNote(); if (!isCompleted) onToggleCompleted(exercise.id); onClose(); };
  return <div className="fixed inset-x-0 bottom-0 top-[4.5rem] z-50 flex items-end justify-center bg-slate-950/25 p-0 sm:items-center sm:p-4" dir="rtl">
    <motion.div initial={{opacity:0,y:24}} animate={{opacity:1,y:0}} className="relative flex max-h-[calc(100dvh-5rem)] w-full max-w-lg flex-col overflow-y-auto rounded-t-[2rem] bg-[oklch(98%_0.012_80)] shadow-2xl dark:bg-[oklch(19%_0.02_265)] sm:rounded-[2rem]">
      <header className="sticky top-0 z-20 flex items-center gap-3 border-b border-[oklch(89%_0.025_80)] bg-[oklch(98%_0.012_80_/_0.96)] px-5 py-4 backdrop-blur-md dark:border-slate-800 dark:bg-[oklch(19%_0.02_265_/_0.96)]"><button onClick={onClose} aria-label="بازگشت" className="flex h-10 w-10 items-center justify-center rounded-xl bg-[oklch(93%_0.025_265)] text-slate-600 active:scale-95 dark:bg-slate-800 dark:text-slate-200"><ArrowRight size={18}/></button><div className="min-w-0 flex-1"><small className="block text-[10px] font-black text-[oklch(50%_0.12_265)]">تمرین‌های یار</small><b className="block truncate text-sm text-slate-900 dark:text-white">{cleanTitle(exercise.title)}</b></div><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[oklch(94%_0.035_175)] text-[oklch(45%_0.10_175)]"><Timer size={17}/></span></header>
      <main className="space-y-4 p-5 sm:p-7">
        {showSafety && exercise.safetyLevel !== 'standard' && <div className="relative flex gap-3 rounded-2xl border border-[oklch(87%_0.05_55)] bg-[oklch(96%_0.035_55)] p-4 text-xs leading-6 text-[oklch(38%_0.08_45)] dark:border-amber-900/40 dark:bg-amber-950/25 dark:text-amber-100"><ShieldAlert size={18} className="mt-0.5 shrink-0"/><div><b className="block">هشدار آرامش و ایمنی</b>{safetyText}</div><button onClick={dismissSafety} aria-label="بستن هشدار" className="absolute left-2 top-2 flex h-8 w-8 items-center justify-center rounded-lg text-amber-700 dark:text-amber-200"><X size={15}/></button></div>}
        <section className="rounded-[1.6rem] bg-[oklch(95%_0.025_265)] p-4 dark:bg-slate-900"><div className="flex items-center gap-2 text-xs font-black text-[oklch(45%_0.11_265)]"><span className="rounded-xl bg-[oklch(88%_0.04_265)] px-2 py-1">{exercise.category}</span><span>تمرین یار</span></div><button onClick={() => setShowInfo(v=>!v)} className="mt-3 flex w-full items-center justify-between text-right"><h1 className="text-xl font-black leading-8 text-slate-900 dark:text-white">{cleanTitle(exercise.title)}</h1>{showInfo?<ChevronUp size={18}/>:<ChevronDown size={18}/>}</button><AnimatePresence initial={false}>{showInfo&&<motion.p initial={{opacity:0,height:0}} animate={{opacity:1,height:'auto'}} exit={{opacity:0,height:0}} className="pt-2 text-xs leading-6 text-slate-600 dark:text-slate-300">{exercise.description}</motion.p>}</AnimatePresence></section>
        <section className="flex items-center justify-between rounded-[1.35rem] bg-[oklch(96%_0.025_175)] px-4 py-3 dark:bg-emerald-950/25"><b className="font-mono text-xl tabular-nums text-slate-900 dark:text-white">{time}</b><button onClick={()=>setRunning(v=>!v)} disabled={seconds===0} className="flex min-h-9 items-center gap-1.5 rounded-xl bg-[oklch(43%_0.11_175)] px-3 text-[11px] font-black text-white disabled:opacity-40"><Timer size={14}/>{running?'مکث':'شروع'}</button></section>
        <section className="rounded-[1.6rem] border border-[oklch(88%_0.025_265)] bg-[oklch(99%_0.006_265)] p-5 dark:border-slate-700 dark:bg-slate-900"><div className="mb-4 flex items-center justify-between"><span className="text-xs font-black text-slate-500">مرحله {toPersianDigits(current.stepNumber)} از {toPersianDigits(exercise.steps.length)}</span><div className="flex gap-1">{exercise.steps.map((_,i)=><span key={i} className={`h-1.5 rounded-full transition-all ${i===step?'w-7 bg-[oklch(50%_0.12_175)]':i<step?'w-2 bg-[oklch(65%_0.10_175)]':'w-2 bg-slate-200 dark:bg-slate-700'}`}/>)}</div></div><h2 className="text-base font-black text-slate-900 dark:text-white">{current.title}</h2><p className="mt-3 text-sm font-semibold leading-7 text-slate-700 dark:text-slate-200">{current.instruction}</p>{current.promptInput&&<p className="mt-3 rounded-xl bg-[oklch(96%_0.03_55)] p-3 text-xs font-bold leading-6 text-[oklch(40%_0.08_45)]">🗣️ {current.promptInput}</p>}{current.tip&&<p className="mt-3 rounded-xl bg-[oklch(95%_0.035_175)] p-3 text-[11px] leading-6 text-slate-700 dark:bg-emerald-950/30 dark:text-slate-200">💡 نکته: {current.tip}</p>}</section>
        <section><div className="mb-2 flex items-center justify-between"><label className="text-xs font-black text-slate-700 dark:text-slate-200">یادداشت تمرین</label>{saved&&<span className="flex items-center gap-1 text-[10px] font-black text-emerald-600"><Check size={13}/> ذخیره شد</span>}</div><textarea value={note} onChange={e=>setNote(e.target.value)} rows={3} placeholder="یک جمله درباره تجربه‌ات بنویس" className="w-full rounded-2xl border border-slate-200 bg-[oklch(99%_0.006_80)] p-3 text-xs leading-6 dark:border-slate-700 dark:bg-slate-900 dark:text-white"/><button onClick={saveNote} className="mt-2 flex min-h-10 items-center gap-1 rounded-xl bg-slate-100 px-3 text-[11px] font-black text-slate-600 dark:bg-slate-800 dark:text-slate-200"><Save size={13}/>ذخیره یادداشت</button></section>
        <footer className="flex gap-2 border-t border-slate-200 pt-4 dark:border-slate-800"><button onClick={()=>setStep(v=>Math.max(0,v-1))} disabled={step===0} className="min-h-12 rounded-xl border border-slate-200 px-4 text-xs font-black disabled:opacity-30 dark:border-slate-700"><ArrowRight size={15}/></button>{step<exercise.steps.length-1?<button onClick={()=>setStep(v=>v+1)} className="flex-1 rounded-xl bg-[oklch(43%_0.11_175)] text-xs font-black text-white">مرحله بعد <ArrowLeft size={15} className="inline"/></button>:<button onClick={finish} className="flex-1 rounded-xl bg-[oklch(43%_0.11_175)] text-xs font-black text-white"><Sparkles size={15} className="inline ml-1"/>اتمام تمرین</button>}</footer>
      </main>
    </motion.div>
  </div>;
};
