import React, { useState } from 'react';
import { motion } from 'motion/react';
import { BellRing, Check, Clock3, MoonStar, SunMedium, X } from 'lucide-react';
interface Props { isOpen: boolean; onEnable: () => Promise<boolean>; onLater: () => void; }
export const NotificationPermissionPrompt: React.FC<Props> = ({ isOpen, onEnable, onLater }) => {
  const [loading,setLoading]=useState(false),[failed,setFailed]=useState(false);
  if (!isOpen) return null;
  const enable=async()=>{setLoading(true);setFailed(false);try{const granted=await onEnable();if(!granted)setFailed(true);}catch{setFailed(true);}finally{setLoading(false);}};
  return <div className="fixed inset-0 z-[130] flex items-end justify-center bg-[oklch(22%_0.025_315_/_0.48)] p-0 sm:items-center sm:p-5" dir="rtl"><motion.section role="dialog" aria-modal="true" aria-labelledby="notification-permission-title" initial={{opacity:0,y:28}} animate={{opacity:1,y:0}} transition={{duration:.42,ease:[.16,1,.3,1]}} className="w-full max-w-md overflow-hidden rounded-t-[2rem] bg-[oklch(98%_0.012_320)] px-5 pb-[calc(env(safe-area-inset-bottom)+1.25rem)] pt-5 shadow-2xl dark:bg-[oklch(19%_0.026_290)] sm:rounded-[2rem]">
    <div className="flex items-start justify-between"><div className="relative flex h-16 w-16 items-center justify-center rounded-[1.4rem] bg-[oklch(88%_0.09_325)] text-[oklch(45%_0.17_325)]"><BellRing size={28}/><span className="absolute -left-1 -top-1 flex h-6 w-6 items-center justify-center rounded-full bg-[oklch(55%_0.16_155)] text-white"><Check size={13}/></span></div><button onClick={onLater} aria-label="بعداً" className="flex h-11 w-11 items-center justify-center rounded-2xl text-slate-400 active:scale-95"><X size={20}/></button></div>
    <p className="mt-6 text-xs font-black text-[oklch(48%_0.15_325)]">یک یادآوری، نه مزاحمت</p><h2 id="notification-permission-title" className="mt-2 text-2xl font-black leading-9 text-slate-900 dark:text-white">روزی دو جمله کوتاه برای رابطه‌تان</h2><p className="mt-3 text-sm leading-7 text-slate-500 dark:text-slate-300">یار صبح و شب فقط یک تلنگر کوچک می‌فرستد. بدون تبلیغ، بدون شلوغی.</p>
    <div className="mt-6 overflow-hidden rounded-[1.4rem] border border-[oklch(88%_0.025_320)] bg-[oklch(99%_0.006_320)] dark:border-slate-700 dark:bg-slate-800"><div className="flex items-center gap-3 px-4 py-3.5"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[oklch(93%_0.06_80)] text-[oklch(55%_0.14_70)]"><SunMedium size={19}/></span><span className="flex-1"><b className="block text-sm text-slate-800 dark:text-white">صبح، ساعت ۱۰</b><small className="mt-1 block text-[11px] text-slate-500">یک شروع آرام و کاربردی</small></span><Clock3 size={16} className="text-slate-300"/></div><div className="mx-4 h-px bg-[oklch(91%_0.015_320)] dark:bg-slate-700"/><div className="flex items-center gap-3 px-4 py-3.5"><span className="flex h-10 w-10 items-center justify-center rounded-2xl bg-[oklch(92%_0.055_285)] text-[oklch(50%_0.15_285)]"><MoonStar size={19}/></span><span className="flex-1"><b className="block text-sm text-slate-800 dark:text-white">شب، ساعت ۲۰:۳۰</b><small className="mt-1 block text-[11px] text-slate-500">یک مکث کوتاه دونفره</small></span><Clock3 size={16} className="text-slate-300"/></div></div>
    {failed&&<p role="alert" className="mt-4 rounded-2xl bg-[oklch(94%_0.035_25)] px-4 py-3 text-xs leading-6 text-[oklch(45%_0.15_25)]">مجوز فعال نشد. هر وقت خواستی از تنظیمات یار دوباره امتحان کن.</p>}
    <button disabled={loading} onClick={enable} className="mt-6 flex min-h-14 w-full items-center justify-center gap-2 rounded-[1.2rem] bg-[oklch(48%_0.17_325)] text-sm font-black text-white transition-transform active:scale-[.98] disabled:opacity-60"><BellRing size={18}/>{loading?'در حال فعال‌سازی...':'فعال کردن دو یادآوری روزانه'}</button><button onClick={onLater} className="mt-2 min-h-11 w-full text-xs font-black text-slate-400">فعلاً نه</button>
  </motion.section></div>;
};
