import React,{useState} from 'react';
import {ChevronDown,Info,BookOpen,Compass,Sparkles,HeartHandshake,Home,Activity,Settings2} from 'lucide-react';
import {motion,AnimatePresence} from 'motion/react';

type Kind='home'|'library'|'journeys'|'exercises'|'couple'|'cycle'|'settings';
const DATA:Record<Kind,{eyebrow:string;title:string;body:string;icon:React.ReactNode;color:string}>={
 home:{eyebrow:'قدم امروزت',title:'خانه یار',body:'اینجا هر روز یک قدم کوچک، یک پیشنهاد متناسب با حال تو و راهی برای نزدیک‌تر شدن پیدا می‌کنی.',icon:<Home size={18}/>,color:'oklch(54% 0.15 300)'},
 library:{eyebrow:'کتابخانه یار',title:'چیزی برای فهمیدن',body:'مقاله‌ها کوتاه و کاربردی‌اند؛ از یک موقعیت واقعی شروع می‌کنند و در پایان به یک جمله یا کار قابل‌انجام برای رابطه می‌رسند.',icon:<BookOpen size={18}/>,color:'oklch(54% 0.15 300)'},
 journeys:{eyebrow:'مسیرهای یار',title:'از دانستن تا تغییر',body:'هر مسیر به ایستگاه‌های کوچک تقسیم شده: یک مفهوم ساده، یک مکث و یک کار واقعی که می‌توانید همان روز امتحان کنید.',icon:<Compass size={18}/>,color:'oklch(55% 0.15 300)'},
 exercises:{eyebrow:'تمرین‌های یار',title:'کمتر توضیح، بیشتر تجربه',body:'یک تمرین را انتخاب کن و فقط همان یک قدم را انجام بده. لازم نیست رابطه را یک‌روزه حل کنی.',icon:<Sparkles size={18}/>,color:'oklch(52% 0.14 158)'},
 couple:{eyebrow:'فضای مشترک رابطه',title:'اتاق ما',body:'حال امروز، روند رابطه، خاطرات و قرارهای شما اینجا کنار هم می‌نشینند تا از ثبت کردن به یک اقدام کوچک برسید.',icon:<HeartHandshake size={18}/>,color:'oklch(54% 0.15 300)'},
 cycle:{eyebrow:'بدن، خلق، رابطه',title:'چرخه قاعدگی',body:'چرخه قرار نیست رفتار تو را تعریف کند. کمک می‌کند الگوی حال، انرژی و نیازهای رابطه‌ای خودت را بشناسی.',icon:<Activity size={18}/>,color:'oklch(58% 0.14 330)'},
 settings:{eyebrow:'کنترل تجربه یار',title:'تنظیمات',body:'اطلاعات شخصی، حریم داده‌ها و ابزارهای آرام‌سازی را از اینجا مدیریت کن.',icon:<Settings2 size={18}/>,color:'oklch(54% 0.15 300)'}
};
export const PageIntroAccordion=({kind,defaultOpen=false}:{kind:Kind;defaultOpen?:boolean})=>{const [open,setOpen]=useState(defaultOpen),d=DATA[kind];return <section className="mb-5 overflow-hidden rounded-[1.65rem] bg-[oklch(96%_0.025_145)] shadow-[0_8px_24px_oklch(48%_0.05_145_/_0.07)] dark:bg-slate-900" dir="rtl"><button onClick={()=>setOpen(v=>!v)} aria-expanded={open} className="flex min-h-16 w-full items-center gap-3 px-4 text-right active:scale-[.99]"><span className="flex h-10 w-10 shrink-0 items-center justify-center rounded-2xl bg-[oklch(99%_0.008_145)]" style={{color:d.color}}>{d.icon}</span><span className="min-w-0 flex-1"><small className="block text-[10px] font-black" style={{color:d.color}}>{d.eyebrow}</small><b className="mt-0.5 block text-base font-black text-slate-900 dark:text-white">{d.title}</b></span><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-[oklch(99%_0.008_145)] text-slate-500 transition-transform dark:bg-slate-800" style={{transform:open?'rotate(180deg)':'rotate(0deg)'}}><ChevronDown size={17}/></span></button><AnimatePresence initial={false}>{open&&<motion.div initial={{height:0,opacity:0}} animate={{height:'auto',opacity:1}} exit={{height:0,opacity:0}} transition={{duration:.25,ease:[.16,1,.3,1]}}><div className="flex gap-3 px-4 pb-4 pt-1"><Info size={16} className="mt-1 shrink-0" style={{color:d.color}}/><p className="text-sm leading-7 text-slate-600 dark:text-slate-300">{d.body}</p></div></motion.div>}</AnimatePresence></section>};
